### ISSUE TITLE
Unexpected attribute parse behaviour in 3.0.0-rc.0

### ISSUE THREAD

**Issue by andyjansson** [postcss/postcss-selector-parser#115] opened 2017-08-15 07:12 UTC
One of our users reported an issue with the [new alpha of cssnano](https://github.com/ben-eb/cssnano/issues/400). Upon examining the issue more closely I discovered that it fails on the following [selector from the `angular-material` package](https://github.com/angular/material/blob/72d068593b7f353d32f8308870d2b0d1c7c759c9/src/core/services/layout/layout.scss#L5):

```css
[ng\:cloak]
```

This seems to have to do with a change to `postcss-selector-parser` affecting how attributes are parsed. Compare the following:

`3.0.0-rc.0`:

```js
Attribute {
  ...
  attribute: 'ng',
  value: '\\:',
  raws: { unquoted: '\\:' },
  spaces: { before: '', after: '' },
  ...
}
```

`v2.2.3`: 

```js
Attribute {
  ...
  operator: undefined,
  value: undefined,
  attribute: 'ng\\:cloak',
  spaces: { before: '', after: '' },
  raws: {},
  ...
}
```

While the changelog does mention the possibility of breaking changes, I think this is likely a bug. 

\cc @ben-eb

**Comment by chriseppstein** [comment] 2017-10-24 17:32
There's some issue in escape handling in the selector parser. it's also not clear to me that characters that need to be escaped are properly escaped in output of css, so just being able to parse this may not be enough because we need to be able to round-trip. -- maybe postcss itself takes care of the escaping, I'm not sure. If so, it should probably own the unescaping as well before postcss-selector-parser ever sees it.

We have to be careful here because different tools may have different expectations around whether a selector string is escaped or not. There's currently no configuration or output options around this and it can get really tricky, really fast. For instance, should we unescape unicode hex sequences into the corresponding utf-8 characters like the browser does? If we don't then two selectors that are actually byte-level equivalent to the browser would appear as distinct to the naive user.

I suspect this is a can of worms that will precipitate a new major release. What I'd suggest for now is that you make a small postcss plugin that preprocesses your selectors with colons to something we can handle (E.g. `[ng-colon-cloak]` and then post-process them back to colons after minification.

**Comment by chriseppstein** [comment] 2017-10-24 17:33
@ai I'm not familiar with how postcss handles escaping/unescaping -- plz advise.

**Comment by ai** [comment] 2017-10-24 17:35
Is `\` a universal escape symbol in CSS?

CSS has a different was to escape `\ 22` any symbols.

For this case, I think, we should check how browser parses it.

**Comment by chriseppstein** [comment] 2017-10-24 17:53
@ai yes. CSS has a generalized escape syntax that can be used just about anywhere and ident or string can appear.

https://mathiasbynens.be/notes/css-escapes is a good writeup on it.

Sass unescapes all characters during parse and then escapes them during stringification so that the AST is always in the domain of UTF-8 encoding -- but sass always parses the entire document -- not true for postcss where a tool like `postcss-selector-parser` handles parsing parts of the document. If I can only access the unescaped values, this is actually a type of information loss and I can't decide if the user made a mistake in their syntax or not.

I guess postcss doesn't currently handle any escaping? I'm surprised you haven't seen many bugs about it. my guess would be that, at least for `rule.selector`, `decl.prop`, `decl.value`, `atRule.name`, `atRule.params`, `comment.value`, there should be access to an escaped value and to an unescaped value -- backwards compat may dictate which is the default. Then the tool can decide which to process. Setters may be needed to ensure consistency between them during ast manipulation.

I think most devs won't know about css escapes or how to handle them and will have many subtle bugs in the general case that they don't even test for.

**Comment by ai** [comment] 2017-10-24 17:55
PostCSS handles escaping for `{`, `(` and another document syntax. But value and selectors are not parsed.

What API do you suggest?

**Comment by chriseppstein** [comment] 2017-10-24 18:27
@ai My preference is that if there's any escape in the source string, postcss would unescape it for the primary value that devs interact with. I think this is the most dev friendly use case and would cause the fewest bugs overall -- but it may be a considered a breaking change depending on your philosophical stance about what constitutes a breaking change.

In this api, any value with an escape sequence would keep the escaped value around as a `raws` value. E.g. `rule.raws.selector`.

Example:

```css
.my\\stupid\\class { custom\:prop: dear\agod\Awhy; }
```

would parse to:

```js
// Rule:
{
  type: "rule",
   selector: ".my\\stupid\\class",
   raws: { escaped: {selector: ".my\\\\stupid\\\\class" } },
   nodes: [...]
}

// Declaration
{
    type: "decl",
    prop: "custom:prop",
    value: "dear\ngod\nwhy",
    raws: { escaped: {prop: "custom\\:prop", value: "dear\\agod\\Awhy"}}
}
```

Then during output to string, post css would encode using the specified character set -- note, this would also imply that postcss would get into the business of mutating the document to some extent, because now it is in charge of `@charset` which must always occur at the very start of the output document (aside: I see a lot of invalid documents from postcss already because of this). postcss would also be sure to escape css special characters in any value without requiring a `raws` to be set.

the escaping strategy chosen pretty much dictates a corresponding encoding support because if the encoding is any other than utf-8, you have to escape any character in the unicode character set -- you're no longer unopinionated and can't blame the user for not understanding how css encoding works (hint: basicaly no one understands css encoding) ;)

**Comment by ai** [comment] 2017-10-24 18:29
Sure. We can add it.

Second question: do we have universal escape logic. Will this escape is standard? Will it work in values?

**Comment by chriseppstein** [comment] 2017-10-24 18:38
@ai css escapes are the same in all places where an ident or string can be found but you can't use an unicode escape to mean a css sigil that is meaningful to the parser -- it would always treat that character as part of an ident or string sequence.

https://www.w3.org/TR/css-syntax-3/#escaping

**Comment by ai** [comment] 2017-10-24 18:47
OK. I will think about it after ReactiveConf. It could take few weeks. As quick fix you can add some `escape(value)` function.

**Comment by chriseppstein** [comment] 2017-10-24 19:02
@ai hmmm. maybe postcss can't handle escaping with its current api. I'm thinking about some use cases where it would be impossible for it to decide what to do. Sass handles this by exposing fine-grained ast objects for values and in selectors but postcss lacks this.
E.g. postcss really cannot decide if a property set to `"foo"` is a string `foo` or an ident containing escaped quote values. I suspect that postcss would have to define an ast for selectors and values to get this right.

**Comment by evilebottnawi** [comment] 2018-01-19 12:21
@ai friendly ping, what is status?

**Comment by ai** [comment] 2018-01-19 12:23
It can’t be solved in the core in next month (moving to US, crazy time). Solve it temporary in this parser.

**Comment by evilebottnawi** [comment] 2018-03-21 08:52
@ai friendly ping, it is one problem what stop `prettier` don't use `3` version

**Comment by ai** [comment] 2018-03-21 17:35
@evilebottnawi can you remind me what we need to change in PostCSS core?

**Comment by evilebottnawi** [comment] 2018-03-21 17:43
@ai solve this problem :smile: looks problem with escaping need more deep investigate, contributors unavailable, i put all failing tests here and investigate where we should fix problem. Also i have couple fixes . If contributors still unavailable, can you review and release new version? If you want i can maintain this project, `prettier` and `stylelint` need this package.

**Comment by ai** [comment] 2018-03-21 17:50
@evilebottnawi contributors is not a problem. I can use the power of out Cult of Martians. But in this case, we will put escaping to the parser. Putting it to the core is dangerous and requires more time to think.

I will make Cult of Martians task this Friday.

**Comment by chriseppstein** [comment] 2018-03-21 17:56
I can fix this in the selector parser. After thinking about it, I don't think it's fixable in core without making this module part of the core and in that case I still have to fix it.

I have a few other patches to get out. I'll take a swing at this today.

**Comment by chriseppstein** [comment] 2018-03-21 17:59
@ai do you know if there is there any escaping/unescaping utilities in postcss or as an npm module  that I can use? 🤔

**Comment by ai** [comment] 2018-03-21 18:02
@chriseppstein nope, I do it my self directly in the parser. But I think there should be modules.

**Comment by chriseppstein** [comment] 2018-03-22 03:05
Unfortunately I didn’t get a chance to work on this today. 😔

**Comment by ai** [comment] 2018-03-25 23:24
Awesome! You are the best :). Thank for escaping library recommendation.

**Comment by evilebottnawi** [comment] 2018-03-26 13:31
@chriseppstein 
Problem in 3 version:
1. Don't parser attribute selector with namespace according spec:
```css
[  |att  ] {}
```
Throw error. 
From spec:
```
attrib
  : '[' S* [ namespace_prefix ]? IDENT S*
        [ [ PREFIXMATCH |
            SUFFIXMATCH |
            SUBSTRINGMATCH |
            '=' |
            INCLUDES |
            DASHMATCH ] S* [ IDENT | STRING ] S*
        ]? ']'
```
2. Lost non standard modificator in attribute selector:
```css
a[href="foo" y] {}
```
Maybe better save this in `raws` :+1: 
3. Don't parser attribute selector with function. In 2 version all works fine
```css
a[id=func('foo')] {}
```
4. Invalid parser selector ending comment
```css
.bar /* comment 3 */ {
   display: block;
}
```
Output:
```
ClassName {
           value: 'bar',
           source: [Object],
           sourceIndex: 0,
           spaces: [Object],
           type: 'selector-class' },
         Combinator {
           value: ' ',
           source: [Object],
           sourceIndex: 4,
           spaces: [Object],
           type: 'selector-combinator' },
         Comment {
           value: '/* comment 3 */',
           source: [Object],
           sourceIndex: 5,
           spaces: [Object],
           type: 'selector-comment' } ]
```
Should don't have `selector-combinator`
5. Lose `$` in attribute selector, maybe in other place too
Input:
```scss
[#{$Keep}] {
  prop: val;
}
```
Contain `_attribute: '#{Keep}',` without `$`

**Comment by chriseppstein** [comment] 2018-03-26 17:28
@evilebottnawi Thanks, I will look into these issues. Did you get a chance to review the new APIs and "escape by default" strategy? Do they look ok to you?

**Comment by chriseppstein** [comment] 2018-03-26 23:09
I wrote up a more comprehensive explanation of this effort. Hopefully this will make it easier to discern the planned changes compared to having to suss it out from the diff: https://github.com/postcss/postcss-selector-parser/pull/133

**Comment by chriseppstein** [comment] 2018-03-27 11:02
@evilebottnawi 

1. An attribute in the default namespace is parsed without error here: https://github.com/postcss/postcss-selector-parser/blob/escape-handling/src/__tests__/namespaces.js#L53 If you are getting an error on this branch, please file a new issue with details.
2. I got non-standard attribute modifiers working in 7b49c55, but I want to follow up with a [small api change](https://github.com/postcss/postcss-selector-parser/issues/134)
3. What is the use case for this nonstandard syntax of functions as attribute values. Why can't you just escape the illegal characters? (E.g. `[id=func\(\'foo\'\)]`)
4. I can reproduce this. Will look into it tomorrow.

**Comment by evilebottnawi** [comment] 2018-03-27 11:08
@chriseppstein 
1. add spaces (newlinews) before `[` and after `]`.
3. it is part of tests of prettier, o don't know who use function inside in `attribute` selector. Maybe postcss have plugin for this :confused:

**Comment by chriseppstein** [comment] 2018-03-28 22:40
@evilebottnawi ok. thanks, I reproduced and fixed the spaces before the namespace prefix.

regarding the function as a bare value: I'm not going to support that syntax without a really great reason and to do so. And I'd need to have a much greater understanding of what is going on. I understand that this will be a regression for some number of users. I guess that will be needed as a  forcing function to understand the use case correctly so I can think about it.

**Comment by evilebottnawi** [comment] 2018-03-29 09:37
@chriseppstein i just remove invalid tests :+1:

**Comment by chriseppstein** [comment] 2018-03-30 00:32
#133 has landed on master and many issues relating to escapes are sorted out now.

**Closed by chriseppstein** 2018-03-30 00:32 UTC
Labels: bug, help wanted, spec-violation
